USE BS;
Go
CREATE TABLE Books(
BooksID INT PRIMARY KEY NOT NULL,
Title VARCHAR (100) NOT NULL,
Genre VARCHAR (100),
Price INT NOT NULL,
AuthorID INT NOT NULL
FOREIGN KEY (AuthorID)
REFERENCES Authors (AuthorID)
);



